### ISSUE TITLE
[.cmd] module should accept that last line is a comment

### ISSUE THREAD

**Issue by vnadot** [epics-extensions/tree-sitter-epics#3]
end of my cmd file:
``
#=================================================================
#
```
tree-sitter messgae:
```
MISSING "\n"
```
fix:
``
#=================================================================
#

```
module should accept that last line is a comment (but it should not accept something else). IEE .cmd template finishes with '#'

**Comment by anjohnson** [comment]
The Single Unix Specification says that text files *must* end in a newline; if a file doesn't have a `\n` as the last character it isn't a text file. All Unix text editors put a newline on the end of text files automatically, but unfortunately Microsoft's OSs don't require that and other editors have added settings which allow files to end without a final newline. This requirement makes it easier to write parsers, which then don't have to have special handling for parsing the last line of a file when the EOF flag gets raised.

Thus personally I would see this tree-sitter message as correct. Git diff shows a similar warning.

**Comment by vnadot** [comment]
Indeed, you're right, it seems possible by default on my linux text editor (vscode) to remove the EOF flag. This strange behavior introduced the issue in my cmd file for ````_tree-sitter-epics``_. I close the issue, thanks !
