### ISSUE TITLE
[.cmd] redirection must be inside quotes ?

### ISSUE THREAD

**Issue by vnadot** [epics-extensions/tree-sitter-epics#4]
line
```
dbl > pvlist_${IOCNAME}.dbl
```
tree-sitter message:
```
    (ERROR [56, 0] - [56, 13])
    (macro_expansion [56, 13] - [56, 23])
    (ERROR [56, 23] - [57, 17])
```
fix:
```
 dbl > "pvlist_${IOCNAME}.dbl"
 ```
 could you accept that the redirection is not between quotes ?

**Comment by minijackson** [comment]
This is a macro issue, that I can't do much about. Although I'd like to support this case, personally I'd say that if `${IOCNAME}` contains a space, you'd run into some trouble, and should quote the path.
